export default {
  data: [
    {
      screen_ID: "24",
      screen_data: {
        ob: "Yes",
        next_page: 2,
        analysis: [
          {
            hash: "98ec398023ea3ed3b0618a592259c4d1",
            article_title: "3 Great Stocks to Buy for 2022 and Hold for Years",
            article_ID: 200612015,
            article_masterid: 0,
            article_time: 1639829640,
            article_is_video: "No",
            article_author: "Zacks Investment Research",
            article_author_ID: "101093114",
            author_num_articles: "159946",
            article_data: "",
            article_href:
              "http://www.investing.com/analysis/3-great-stocks-to-buy-for-2022-and-hold-for-years-200612015",
            itemType: "Content",
            itemCategoryTags: "282",
            related_image:
              "https://d1-invdn-com.investing.com/company_logo/101093114_1461491293.png",
            comments_cnt: "0",
            is_partial: "yes",
            body_len: 12567,
          },
          {
            hash: "f608319578c790402488777ac12e87ff",
            article_title:
              "PlanB Reverses $100K BTC Prediction, Ethereum Whales Accumulate; HBAR Spikes 30% on Metaverse Foray",
            article_ID: 200612014,
            article_masterid: 125142,
            article_time: 1639873213,
            article_is_video: "No",
            article_author: "KryptoMoney",
            article_author_ID: "125142",
            author_num_articles: 0,
            article_href: "",
            third_party_url: "https://invst.ly/wxcg5",
            article_data:
              '<p>As Bitcoin wavers beneath the $50k barrier, Stock to flow (S2F) creator, PlanB believes BTC needs a ”small miracle” to reach the end-of year-$100k mark. In a Dec. 18 tweet, He says ”Bitcoin needs a small miracle for a 100K Christmas. Will I ditch the S2F model if this does not happen? Nah, I actually […]</p>\n<p>The post PlanB Reverses $100K BTC Prediction, Ethereum Whales Accumulate; HBAR Spikes 30% on Metaverse Foray appeared first on Latest Crypto News.\nPlanB Reverses $100K BTC Prediction, Ethereum Whales Accumulate; HBAR Spikes 30% on Metaverse Foray was first posted on December 18, 2021 at 7:20 pm.©2021 "Latest Crypto News". Use of this feed is for personal non-commercial use only. If you are not reading this article in your feed reader, then the site is guilty of copyright infringement. Please contact me at info@kryptomoney.com</p>',
            itemType: "External",
            itemCategoryTags: "302",
            related_image:
              "https://i-invdn-com.investing.com/companies_logos/analysis3rdparty.jpg",
            comments_cnt: "0",
            is_partial: "no",
            body_len: 860,
          },
          {
            hash: "14da4595d68a4dd2191a1880ac427937",
            article_title:
              "LUNA, Loopring, ENJ, SHIB Are Tokens To Watch As BTC Attempts Rebound; XRP Holders To Receive $1 Billion Airdrop",
            article_ID: 200612013,
            article_masterid: 125142,
            article_time: 1639865437,
            article_is_video: "No",
            article_author: "KryptoMoney",
            article_author_ID: "125142",
            author_num_articles: 0,
            article_href: "",
            third_party_url: "https://invst.ly/wxc8y",
            article_data:
              '<p>Bitcoin is struggling to rebound after dipping to lows of $45,515 on Dec. 17. The crypto market following Bitcoin’s lead dipped on Friday after the U.S. Financial Stability Oversight Council published a report warning Congress about stablecoin and decentralized finance (DeFi) risks. The news that SEC had delayed its decision on Grayscale and Bitwise spot […]</p>\n<p>The post LUNA, Loopring, ENJ, SHIB Are Tokens To Watch As BTC Attempts Rebound; XRP Holders To Receive $1 Billion Airdrop appeared first on Latest Crypto News.\nLUNA, Loopring, ENJ, SHIB Are Tokens To Watch As BTC Attempts Rebound; XRP Holders To Receive $1 Billion Airdrop was first posted on December 18, 2021 at 5:10 pm.©2021 "Latest Crypto News". Use of this feed is for personal non-commercial use only. If you are not reading this article in your feed reader, then the site is guilty of copyright infringement. Please contact me at info@kryptomoney.com</p>',
            itemType: "External",
            itemCategoryTags: "302",
            related_image:
              "https://i-invdn-com.investing.com/companies_logos/analysis3rdparty.jpg",
            comments_cnt: "0",
            is_partial: "no",
            body_len: 937,
          },
          {
            hash: "ac2b2ec845f724e1db5073881dca979f",
            article_title:
              "Bitcoin Price Analysis: Despite the Bearishness, Onchain Might Suggest a Supply Shock",
            article_ID: 200612011,
            article_masterid: 125142,
            article_time: 1639858903,
            article_is_video: "No",
            article_author: "CryptoPotato",
            article_author_ID: "125142",
            author_num_articles: 0,
            article_href: "",
            third_party_url: "https://invst.ly/wxc0x",
            article_data:
              "<p>According to Reuters, the Russian central bank wants to ban investments in cryptocurrencies in the country. Following the bearish news, Bitcoin’s price fell to near $48.5k in the spot market. In the options market the last 48 hours, many options traders sold Calls and bought Puts to hedge for the near-term expiries. Multi expiry skew […]</p>",
            itemType: "External",
            itemCategoryTags: "0",
            related_image:
              "https://i-invdn-com.investing.com/companies_logos/analysis3rdparty.jpg",
            comments_cnt: "0",
            is_partial: "no",
            body_len: 350,
          },
          {
            hash: "99eb8291058d022d5f3b09d3f5ed4be9",
            article_title:
              "BTC/USD Capped Below 47464 Technical Resistance:  Sally Ho's Technical Analysis 19 December 2021 BTC",
            article_ID: 200612009,
            article_masterid: 125142,
            article_time: 1639850400,
            article_is_video: "No",
            article_author: "CryptoDaily",
            article_author_ID: "125142",
            author_num_articles: 0,
            article_href: "",
            third_party_url: "https://invst.ly/wxbtt",
            article_data: "",
            itemType: "External",
            itemCategoryTags: "302",
            related_image:
              "https://i-invdn-com.investing.com/companies_logos/analysis3rdparty.jpg",
            comments_cnt: "0",
            is_partial: "yes",
            body_len: 2446,
          },
          {
            hash: "98ec398023ea3ed3b0618a592259c4d1",
            article_title: "3 Great Stocks to Buy for 2022 and Hold for Years",
            article_ID: 200612001,
            article_masterid: 0,
            article_time: 1639829640,
            article_is_video: "No",
            article_author: "Zacks Investment Research",
            article_author_ID: "101093114",
            author_num_articles: "159946",
            article_data: "",
            article_href:
              "http://www.investing.com/analysis/3-great-stocks-to-buy-for-2022-and-hold-for-years-200612001",
            itemType: "Content",
            itemCategoryTags: "282",
            related_image:
              "https://d1-invdn-com.investing.com/company_logo/101093114_1461491293.png",
            comments_cnt: "0",
            is_partial: "yes",
            body_len: 12567,
          },
          {
            hash: "14a49afc7b6d7d2452bd43b76298ca6e",
            article_title:
              "Cybersecurity, Inflation De-anchoring, COVID's Legacy",
            article_ID: 200611997,
            article_masterid: 0,
            article_time: 1639730640,
            article_is_video: "No",
            article_author: "Zacks Investment Research",
            article_author_ID: "101093114",
            author_num_articles: "159946",
            article_data: "",
            article_href:
              "http://www.investing.com/analysis/cybersecurity-inflation-deanchoring-covids-legacy-200611997",
            itemType: "Content",
            itemCategoryTags: "282",
            related_image:
              "https://d1-invdn-com.investing.com/company_logo/101093114_1461491293.png",
            comments_cnt: "0",
            is_partial: "yes",
            body_len: 2717,
          },
          {
            hash: "f9706f67c390b68ca7db6914cd89aabc",
            article_title:
              "Kroger's (KR) Indianapolis Fulfillment Network to Aid E-commerce",
            article_ID: 200611994,
            article_masterid: 0,
            article_time: 1639728960,
            article_is_video: "No",
            article_author: "Zacks Investment Research",
            article_author_ID: "101093114",
            author_num_articles: "159946",
            article_data: "",
            article_href:
              "http://www.investing.com/analysis/krogers-kr-indianapolis-fulfillment-network-to-aid-ecommerce-200611994",
            itemType: "Content",
            itemCategoryTags: "282",
            related_image:
              "https://d1-invdn-com.investing.com/company_logo/101093114_1461491293.png",
            comments_cnt: "0",
            is_partial: "yes",
            body_len: 6373,
          },
          {
            hash: "11c76643f3576d1b4725f345c165b133",
            article_title:
              "Synopsys (SNPS) to Buy Back Stock Worth $200M Under ASR Pact",
            article_ID: 200611983,
            article_masterid: 0,
            article_time: 1639722360,
            article_is_video: "No",
            article_author: "Zacks Investment Research",
            article_author_ID: "101093114",
            author_num_articles: "159946",
            article_data: "",
            article_href:
              "http://www.investing.com/analysis/synopsys-snps-to-buy-back-stock-worth-200m-under-asr-pact-200611983",
            itemType: "Content",
            itemCategoryTags: "282",
            related_image:
              "https://d1-invdn-com.investing.com/company_logo/101093114_1461491293.png",
            comments_cnt: "0",
            is_partial: "yes",
            body_len: 5352,
          },
          {
            hash: "1b988d3bdeef626066b56833ea9ec3be",
            article_title:
              "The Zacks Analyst Blog Highlights: Alphabet, Bank of America, S&P Global, ServiceNow and Boeing",
            article_ID: 200611979,
            article_masterid: 0,
            article_time: 1639717260,
            article_is_video: "No",
            article_author: "Zacks Investment Research",
            article_author_ID: "101093114",
            author_num_articles: "159946",
            article_data: "",
            article_href:
              "http://www.investing.com/analysis/the-zacks-analyst-blog-highlights-alphabet-bank-of-america-sp-global-servicenow-and-boeing-200611979",
            itemType: "Content",
            itemCategoryTags: "282",
            related_image:
              "https://d1-invdn-com.investing.com/company_logo/101093114_1461491293.png",
            comments_cnt: "0",
            is_partial: "yes",
            body_len: 6869,
          },
        ],
      },
      screen_layout:
        "[L3],[L3],[L3],[L3],[L3],[L3],[L3],[p100],{[L3],[L3],[L3],[L3],[L3],[L3],[L3],[p100],[L3],[L3],[L3]}*",
    },
  ],
};
